### PR TITLE
Enable wayland backend

### PR DESCRIPTION
**Pull request by Twig6943**
The wayland backend seems to work fine 
Screenshot_20241214_192923

### CODE REVIEW

**Comment by Twig6943** [comment]
(the db lock on the logs is unrelated to this change tldr; I messed something up)

**Comment by hfiguiere** [comment]
duplicate of #82

**Comment by Twig6943** [comment]
So, similar to Krita, this is awaiting this merge request: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/14

**Comment by paperdigits** [comment]
More than that. You're not running on Wayland either, but xwayland. Long story short, dark table doesn't support Wayland and while using it and reporting bugs is encouraged, we do not way to deploy it to a lot of people. Also Wayland is in sufficient feature wise for darktable.

**Pull request closed without merging**
