### PR TITLE
Add missing dependencies

### PR DESCRIPTION
**Pull request by hfiguiere**
This fixes the following issues:

* Issue #4 (supercede PR #24)
* Issue #21 
* Issue #25 
* Issue #27

### CODE REVIEW

**Comment by eszlari** [comment]
Why not OpenEXR / IlmBase 2.3.0?
https://github.com/openexr/openexr/releases/tag/v2.3.0

**Comment by hfiguiere** [comment]
Because I just copied the build steps from blender.

**Comment by hfiguiere** [comment]
Actually openEXR 2.3 doesn't build out of the box.

**Comment by eszlari** [comment]
> Actually openEXR 2.3 doesn't build out of the box.

I had no problem with Krita: https://github.com/flathub/org.kde.krita

**Comment by hfiguiere** [comment]
it doesn't use the same SDK. Doesn't even have the same C++ compiler. 

There is a bug somwehere which involve more work.

**Comment by eszlari** [comment]
Maybe the cmake build works?!

**Comment by hfiguiere** [comment]
FWIW in the darktable sandbox, we get this error:
`checking whether g++ supports C++14 features by default... no` (and subsequeant one)
gcc is 8.2.0

In the Krita sandbox it works and it is gcc 6.4.0

On my system with gcc 8.2.1 (RedHat) it works too.

**Comment by hfiguiere** [comment]
Found a workaround. Now using OpenEXR 2.3.0

**Comment by hfiguiere** [comment]
For the record the problem lies in the global `build-options.cxxflags` that set `-std=c++11` which in turn cause the configure script to fail. I have overridden it for OpenEXR and IlmBase.

**Comment by hfiguiere** [comment]
The PR is ready. Do I need approval to merge?

**Comment by jurf** [comment]
Random comment: you can simplify the cleanups to stuff like `*.la` or `/lib/pkgconfig`, no need to be concrete, it’ll just be forgotten to be updated later.

**Comment by matze** [comment]
I am not sure if this commit message syntax will close the affected issues, if not I will close them manually.

**Pull request merged**
