### PR TITLE
Update to 3.0

### PR DESCRIPTION
**Pull request by matze**
Also integrates the changes from #46.

### CODE REVIEW

**Comment by hfiguiere** [comment]
It fail to build. This is because of darktable-org/darktable#3688

When I asked the other day about "a compiler with graphite support enabled" there was no answer.

**Comment by hfiguiere** [comment]
And pr #46 fails on aarch64 (to update 2.6.3 to the latest SDK)

**Comment by matze** [comment]
> And pr #46 fails on aarch64 (to update 2.6.3 to the latest SDK)
I was thinking of just disabling ARM builds. About the Graphite optimization … I am still googling.

**Comment by hfiguiere** [comment]
FWIW it builds on F31 with gcc. (but not inside the flatpak SDK)

**Comment by matze** [comment]
So what options do we have? Patching those optimizations out?

**Comment by hfiguiere** [comment]
I asked back when I was trying to flatpak the rc on the freedesktop-sdk channel and heard nothing.

Upstream seems to have no concerns about the issue, so much that they won't even try to detect it. (issue was closed without action)

I think the proper solution is to get the toolchain fixed in freedesktop-sdk since things work out of the box on, say, Fedora.

**Comment by hfiguiere** [comment]
Filed a freedesktop-sdk issue;

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/943

**Comment by barthalion** [comment]
I replied there. I can imagine FDO SDK team may be unwilling to fix it for existing releases as it would require major rebuild, but let's wait for their answer.

**Comment by Erick555** [comment]
@hfiguiere freedesktop-sdk runtime on flathub should be fixed now.

**Comment by hfiguiere** [comment]
it's not. I commented on the upstream SDK bug.

**Comment by Erick555** [comment]
@hfiguiere it's fixed only in freedesktop-sdk, you have to wait til gnome releases new 3.34.

**Comment by hfiguiere** [comment]
OK.

For reference https://gitlab.gnome.org/GNOME/gnome-build-meta/merge_requests/501

**Comment by hfiguiere** [comment]
bot, build org.darktable.Darktable

**Comment by hfiguiere** [comment]
It's likely gonna fail. It needs a different version of lensfun.

**Comment by hfiguiere** [comment]
You need this change for `lensfun` modules

```diff
-                    "commit": "3724bdbbfc00e171d5cea2c66fb3668d0f3acebb"
+                    "commit": "b7c7e49a3601690f3225b99a0acbe7272fe68bfa",
+                    "tag": "v0.3.95"
```

**Comment by matze** [comment]
Let's merge it?

**Comment by hfiguiere** [comment]
merged

**Pull request merged**
