### PR TITLE
Add exiftool to the sandbox in support of certain Lua scripts

### PR DESCRIPTION
**Pull request by rrenomeron**
Some Lua scripts supporting automatic styling of photos on import run ``exiftool`` in order to take action based on the imported photo's EXIF.  This adds exiftool and its perl dependency to the sandbox so that it can run.  A more secure approach than #97.

Inspired by https://github.com/flathub/io.github.hvdwofl.jExifToolGUI.

### CODE REVIEW

**Comment by paperdigits** [comment]
Which lua scripts are these?

**Comment by rrenomeron** [comment]
This one: https://bastibe.de/2022-05-04-customizing-darktable-for-fujifilm-cameras.html
and these from the darktable.org repo:
- fujifilm_dynamic_range.lua
- fujifilm_ratings.lua
- enfusedAdvanced.lua

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
The package goes from 91.2MB to 149.1MB

**Comment by rrenomeron** [comment]
That would be the perl runtime needed by Exiftool adding on all those megabytes.

**Comment by paperdigits** [comment]
It'd be much nicer if the lua was modified to use exiv2, which does much the same thing but is already in the sandbox.

Since lua can call anything.... Are we going to support everything?

**Comment by rrenomeron** [comment]
Unfortunately, exiv2 can't display the "Auto Dynamic Range" setting for Fujifilm cameras, since it appears to be buried in the MakerNote.

**Comment by Nalsai** [comment]
Couldn't exiftool be made into an extension? People who need exiftool could install the extension and the package can be kept small for people who don't need it.

**Comment by rrenomeron** [comment]
Something like this looks promising: https://blog.tingping.se/2018/03/18/flatpaking-plugins.html.  I'm happy to give it a try.  @Nalsai, if you know of a better reference for this, please chime in.

**Comment by paperdigits** [comment]
@rrenomeron that seems like the right approach

**Comment by hfiguiere** [comment]
> Couldn't exiftool be made into an extension? People who need exiftool could install the extension and the package can be kept small for people who don't need it.

Given the dependency on Perl, no.

**Comment by hfiguiere** [comment]
> Unfortunately, exiv2 can't display the "Auto Dynamic Range" tag for Fujifilm cameras.

Maybe submitting a patch to Exiv2? That seems to be a better long term solution.

**Comment by hfiguiere** [comment]
See this revived #146.

**Comment by hfiguiere** [comment]
and it was merged. This should be available at the next update.

**Pull request closed without merging**
