### PR TITLE
Update to 3.8.0

### PR DESCRIPTION
**Pull request by hfiguiere**
- Update runtime to GNOME 41
- Update exiv2
- Added Jasper and libheif

### CODE REVIEW

**Comment by hfiguiere** [comment]
We need to build lua 5.4

**Comment by hfiguiere** [comment]
oh and it breaks on aarch64

**Comment by hfiguiere** [comment]
Added lua 5.4 now.

**Comment by paperdigits** [comment]
Aarch64 isn't building on opensuse OBS either, just fyi

**Comment by hfiguiere** [comment]
not the first time.

**Comment by hfiguiere** [comment]
tl;dr if `__DT_CLONE_TARGETS__` definition:

`__has_attribute(target_clones)` is true but the architecture aarch64 isn't checked cause the macro to not be defined. Cooking up a patch.

**Pull request merged**
