### PR TITLE
Add Lua support. Fixes #35.

### LINKED ISSUE #35: Lua support missing
Firstly: Thanks for Darktable as a Flatpak!

I noticed that Lua support is not enabled in the build, which means it's currently not possible to use plugins in the Flatpak build. :cry:

```
$ flatpak run org.darktable.Darktable --version

this is darktable 2.6.2
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support disabled
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled
```

### PR DESCRIPTION
**Pull request by paperdigits**
Use flathub's shared modules to add lua support.

### CODE REVIEW

**Comment by matze** [comment]
Could you rebase against master to pick up your other merged change?

**Comment by paperdigits** [comment]
Well those build failures are annoying. I guess I will try to send some patches upstream to darktable.

**Comment by paperdigits** [comment]
@matze should we patch the AppData file with the <version/> info so the build we succeed again?

**Comment by matze** [comment]
Sure, if you want to you can add another commit here. Otherwise I can spent a few minutes later tonight.

**Comment by paperdigits** [comment]
@matze I'd appreciate if you could do it. I'm not sure exactly which file to patch.

**Comment by paperdigits** [comment]
@matze I'm not sure what I did wrong. I think the patch is getting applied after make is run in DT? I'm not sure.

**Comment by matze** [comment]
Forgot about this PR here. I added release data with the last commits, so could you update this branch here by removing the last commit and rebasing the Lua one on top of master?

**Comment by paperdigits** [comment]
@matze done! Thank you for patching in the AppData stuff.

**Comment by matze** [comment]
Likewise, thanks for adding Lua support ;-)

**Pull request merged**
