### PR TITLE
Added libusb. (Issue #4)

### PR DESCRIPTION
**Pull request by hfiguiere**
OBSOLETE caveat: you have to run with `--device=all`

### CODE REVIEW

**Comment by jurf** [comment]
@hfiguiere if it won’t work without `--device=all`, just add it.

**Comment by hfiguiere** [comment]
I was standing on the cautious side to not give to much permission. If that's ok, I can do that.

**Comment by w-wagner** [comment]
I would like to confirm, that the test build 639 above fixes my issue #26 
The option "--device=all" does not help to find the camera. The build 639 fixes my issues and makes darktable work as usual.
I will use this test build to check for other issues.
Good work! Thanks for the patch! Please merge, if there appear no other new issues!

**Comment by jurf** [comment]
> The option "--device=all" does not help to find the camera.

What’s the context here? In the regular build it won’t help, because it misses `libusb`, but this PR already includes `--device=all` by default.

**Comment by w-wagner** [comment]
Yes right.
I was in a discussion with Hubert Figuière whether `--device=all` will make the release work or not. Maybe this all is a misunderstanding...
The main point is:
My tests confirm that this patch works and solves my issue
In the meantime I am working with the testbuild. I have found no other issues yet.

**Comment by hfiguiere** [comment]
Just to reiterate: with that PR you shouldn't have to add `--device=all` as launch time because it's in the manifest. Originally I didn't add it because I was being cautious to not add broad permissions, but then I updated the PR.

If it doesn't work out of the box, let me know.

**Comment by hfiguiere** [comment]
Superceded by PR #28

**Pull request closed without merging**
