### PR TITLE
Update SDK to 3.34

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by hfiguiere** [comment]
Failure is due to MP code on aarch64

**Comment by paperdigits** [comment]
I don't think we should be building for ARM, it isn't officially supported upstream and the chances of a user having a good experience on available arm hardware is low.

**Comment by hfiguiere** [comment]
If only we could just select the runtime version base on arch. I'd stick to the older runtime for aarch64.

**Comment by hfiguiere** [comment]
Part of #48 . Closing.

**Pull request closed without merging**
